### ISSUE TITLE
Using WithBody function with MultipartFormDataContent object

### ISSUE THREAD

**Issue by natn2323** [djmnz/RestFluencing#13]
AFAIK, there isn't a wait to use `WithBody(string)` with a data type other than string. I'm trying to send an un-serialized MultipartFormDataContent object. Currently, is this possible to do with RestFluencing in general? If not, is this feature going to be implemented?

**Comment by djmnz** [comment]
@natn2323 Unfortunately, we don't have any easy way to introduce that at the moment.

There is a way to do it, but would need to override the HttpClient class and need to create a new IApiRequest object.

Let me know if you would like me to provide you an example of this.

**Comment by natn2323** [comment]
@djmnz Thank you for the reply. Yes, please provide an example of how to override the HttpClient class and how to create the new IApiRequest object.

**Comment by djmnz** [comment]
@natn2323 I created a sample in a feature branch

https://github.com/djmnz/RestFluencing/tree/feature/multipart-request/samples/RestFluencing.Sample.CustomClient

Most of the code is on the "Client" folder.

You can pretty much copy the whole folder to your solution and see if it works.

The usage is on the SampleClient.cs:
``` c#
		    var config = 
			    new RestConfiguration()
				.WithBaseUrl("http://localhost:8080/")
				.UseJsonResponseDeserialiser()
				.UsingMultipartApiClient();

		    config.RequestDefaults.TimeoutInSeconds = 90;

		    config.Post("/")
			    .WithMultipart(r => r.Add(new StringContent("value"), "key"))
			    .Response()
			    .ReturnsStatus(HttpStatusCode.OK);
```

The main bits are:
**Set the special client**
``` C#
.UsingMultipartApiClient();
```

**Modify your content**

``` c#
.WithMultipart(r => r.Add(new StringContent("value"), "key"))
```

To be completely honest, I haven't tested the code, this is more to give you a head-start. Let me know if you have any issues.

**Comment by djmnz** [comment]
@natn2323 I decided to have a go on the sample  and found that it wouldn't have worked. :)

I fixed a bug on Restfluencing.Core to allow to example to work properly. 

Make sure you use the version **1.0.1** 

https://www.nuget.org/packages/RestFluencing/1.0.1.35

Let me know how it goes.

**Comment by natn2323** [comment]
I updated to **1.0.1**.

I modified the code within SampleClient.cs and tested the MultipartForm POST request against my own endpoint. Works like a charm! Please commit--I'd love to start implementing this everywhere in my project!

I'm very grateful for your assistance, @djmnz!

**Comment by natn2323** [comment]
Hi @djmnz,

Any update on when this feature might be available in the master branch?

**Comment by djmnz** [comment]
I will try to do this weekend sorry.

You can still use the code provided as a start, all you may need to do is change namespaces .

________________________________

**Comment by natn2323** [comment]
I tried changing the namespaces, but was unsuccessful in being able to call the new `UsingMultipartApiClient` code.

**Comment by djmnz** [comment]
hi @natn2323 sorry for taking so long to come back to you.

I added the support for multipart content requests in the core library. Version 1.1.0.43

You should be able to use the namespace `RestFluencing.Client.MultipartApiClient` and the extensions are the same as in the original example.

**Comment by natn2323** [comment]
Thank you, @djmnz!
