### ISSUE TITLE
How to get the API response to use in subsequent tests?

### ISSUE THREAD

**Issue by adarmus** [djmnz/RestFluencing#2]
Hi - love the library.

We want to use the ID from one request to construct a second request. How can we access the response model from the first outside of an "assert" expression?

Thanks, Adam

**Comment by marktilleytlc** [comment]
Hi, I work with Adam. If we just add a property to RestResponse:

public IApiClientResponse ApiResponse => Context.Response;

Then we can:
var myResponse = JsonConvert.DeserializeObject< MyResponseModel>(response.ApiResponse.Content);
and access anything we need.

Thanks, Mark

**Comment by adarmus** [comment]
I have added a couple of PRs that allow this to be done (in different ways).

Adam

**Comment by djmnz** [comment]
hey guys @adarmus @marktilleytlc 
Thanks for the feedback and contribution!

As you figured it out, there is not built in way to do what you need. And thanks for creating the Action Rule. 

However I feel that "Action" breaks a little bit the "Fluent" syntax and the Assertion intention of the framework.

I understand the benefit of an action before and after a request, but also an easy way for people to add custom validations.

So do you reckon that the example below would be helpful for you all?

```

string headerValue = "";
string login = "";
Rest.GetFromUrl("https://api.github.com/users/defunkt")
    .WithHeader("User-Agent", "RestFluencing Sample")
    .BeforeRequestDo(context => {
        // you can intercept the request for whatever reason
    })
    .AfterRequestDo(context => {
        // you can intercept the response for whatever reason
    })
    .Response()
    .Returns<GitHubUserModel>(model =>
    {
        // Here you can do action but also do inline specific validations
        // but also access the deserialized response
        login = model.login;
        return true;
    }, "Your reason why it failed - in your case you leave it blank since would never fail.")
    .ReturnsStatus(HttpStatusCode.OK)
    .Assert();


```

I will see if I can crack some of this code this weekend :)

**Comment by adarmus** [comment]
Hi - I understand your concerns, and your suggestion looks good.

Thanks, Adam

**Comment by djmnz** [comment]
I have uploaded the new package that includes the before and after request events and also a ReturnsModel<T> that allows you to write inline validation.

You should still be able to use your custom rules if you added them as part of your project.


```
	// Arrange
	bool callFromRequest = false;
	var config = RestConfigurationHelper.Default();
	var request = config.Get("/null")
		.AfterRequest(context => { callFromRequest = true; });
	// Act
	request.Response().Assert();
	// Assert
	Assert.IsTrue(callFromRequest);
```

And

```
	Rest.Get("/product/apple", _configuration)
		.Response()
		.ReturnsModel<Product>(product => {
			return
				product.Name == "Apple";
		}, "My custom error message")
		.Execute()
		.ShouldPass();
```

**Comment by marktilleytlc** [comment]
Thank you Douglas, I have updated our code to use AfterRequest and it is working well.

Regards

Mark

**Comment by adarmus** [comment]
Great - thanks.

Adam
