### ISSUE TITLE
.NET Standard/Core version

### ISSUE THREAD

**Issue by jmcgowan85cc** [djmnz/RestFluencing#9]
Hi,

Is there a plan to make this framework .NET standard/core compatible?

Regards

**Comment by djmnz** [comment]
I just started the dotnetcore feature branch, mostly done :)

I will try to close it of by this weekend.

https://github.com/djmnz/RestFluencing/tree/feature/dotnetcore

**Comment by jmcgowan85cc** [comment]
Great! Look forward to using it.

Many thanks!

**Comment by djmnz** [comment]
This is done, let me know how it goes :)

https://www.nuget.org/packages/RestFluencing/1.0.0.28

I will be building an AspNetMvc extension package for the issue #8
